version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    # charge automatiquement le fichier .env
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_started

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    # initialiser la BDD
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vite_et_gourmand
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 20s
      retries: 10

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data: